name: Issue to PR with Codex

on:
  issues:
    types: [labeled]

jobs:
  fix_with_codex:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'codex' # Run only when the 'codex' label is applied

    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      - name: Generate patch with Codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          BRANCH="codex/issue-${{ github.event.issue.number }}"
          git switch -c "$BRANCH"

          if [ -d "node_modules" ]; then
            rm -rf node_modules
          fi
          if [ -f "package-lock.json" ]; then
            rm package-lock.json
          fi

          PROMPT="$(printf '%s\\n\\n%s\\n%s\\n' "${{ github.event.issue.title }}" "${{ github.event.issue.body }}" "At the end, run \`npm ci && npm run build\` and ensure no errors occur. Do not modify any files or directories that start with a dot (e.g., .git).")"
          
          codex -a full-auto --quiet "$PROMPT"

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Fix: #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          fi
          
          git push -u origin "$BRANCH"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Fix: #${{ github.event.issue.number }} – ${{ github.event.issue.title }}" \
            --body  "Automated fix generated by Codex CLI." \
            --base  main \
            --head  "$BRANCH"
