
name: Extension Release

on:
  # Manual backup release workflow. Primary pipeline is release.yml (tags: v*).
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            webview-ui/package-lock.json

      - name: Install dependencies (root)
        run: npm ci

      - name: Install dependencies (webview-ui)
        run: npm --prefix webview-ui ci

      - name: Build project (SSR + webview)
        run: npm run build

      - name: Publish to VS Code Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          dependencies: false
          skipDuplicate: true

      - name: Publish to Open VSX
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          registryUrl: https://open-vsx.org
          dependencies: false
          skipDuplicate: true
